services:
  redis:
    image: redis
    ports:
      - 6479:6379
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: example_db
    ports:
      - 28017:27017
